In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Read the data

In [2]:
data = pd.read_csv('train_file.csv')
data.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",335.0,Female,Hispanic or Latino,4,"(29.760427, -95.369803)",H49,1,4,0,Local,7.4793
1,2,1997,"Houston, TX",0,Currently drank alcohol,"at least one drink of alcohol, on at least 1 d...",382.0,Total,Black or African American,4,"(29.760427, -95.369803)",H42,0,3,0,Local,49.6852
2,3,1993,Nevada,0,Had their first drink of alcohol before age 13...,other than a few sips,196.0,Female,White,0,"(39.493240390000494, -117.07184056399967)",H41,1,6,2,State,47.8132
3,4,2017,Pennsylvania,1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",104.0,Male,Asian,4,"(40.79373015200048, -77.86070029399963)",H49,2,2,0,State,3.4554
4,5,2007,"San Francisco, CA",1,Ever took steroids without a doctor's prescrip...,"pills or shots, one or more times during their...",100.0,Female,Multiple Race,4,"(37.77493, -122.419416)",H55,1,7,0,Local,0.0000

In [3]:
data.tail()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
55394,55395,2005,Connecticut,0,Had their first drink of alcohol before age 13...,other than a few sips,541.0,Total,Total,0,"(41.56266102000046, -72.64984095199964)",H41,0,0,2,State,25.7511
55395,55396,2005,Nebraska,1,Currently used marijuana,"also called grass, pot, or weed, one or more t...",595.0,Female,Total,3,"(41.6410409880005, -99.36572062299967)",H48,1,0,1,State,15.1999
55396,55397,2007,Marshall Islands,0,Had their first drink of alcohol before age 13...,other than a few sips,186.0,Female,Total,1,"(6.068302, 171.989379)",H41,1,0,3,Territory,11.8563
55397,55398,2011,Texas,0,Ever drank alcohol,"at least one drink of alcohol, on at least 1 d...",1107.0,Total,Total,0,"(31.827240407000488, -99.42677020599967)",H40,0,0,2,State,74.2424
55398,55399,2001,"Dallas, TX",1,Ever injected any illegal drug,used a needle to inject any illegal drug into ...,348.0,Male,Hispanic or Latino,4,"(32.776664, -96.796988)",H57,2,4,0,Local,6.3482

In [4]:
#data['LocationDesc'].value_counts()

In [5]:
data.keys()

Index(['Patient_ID', 'YEAR', 'LocationDesc', 'Subtopic',
       'Greater_Risk_Question', 'Description', 'Sample_Size', 'Sex', 'Race',
       'Grade', 'GeoLocation', 'QuestionCode', 'StratID1', 'StratID2',
       'StratID3', 'StratificationType', 'Greater_Risk_Probability'],
      dtype='object')

# unwanted columns are 
## Patient_ID,LocationDesc,Description,GeoLocation

In [6]:
#data['Greater_Risk_Question'].value_counts()

In [7]:
data['Race'].value_counts()

Total                                        22252
White                                        13448
Hispanic or Latino                            7855
Black or African American                     7078
Asian                                         2053
Multiple Race                                 1088
Native Hawaiian or Other Pacific Islander      978
American Indian or Alaska Native               647
Name: Race, dtype: int64

In [8]:
data.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",335.0,Female,Hispanic or Latino,4,"(29.760427, -95.369803)",H49,1,4,0,Local,7.4793
1,2,1997,"Houston, TX",0,Currently drank alcohol,"at least one drink of alcohol, on at least 1 d...",382.0,Total,Black or African American,4,"(29.760427, -95.369803)",H42,0,3,0,Local,49.6852
2,3,1993,Nevada,0,Had their first drink of alcohol before age 13...,other than a few sips,196.0,Female,White,0,"(39.493240390000494, -117.07184056399967)",H41,1,6,2,State,47.8132
3,4,2017,Pennsylvania,1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",104.0,Male,Asian,4,"(40.79373015200048, -77.86070029399963)",H49,2,2,0,State,3.4554
4,5,2007,"San Francisco, CA",1,Ever took steroids without a doctor's prescrip...,"pills or shots, one or more times during their...",100.0,Female,Multiple Race,4,"(37.77493, -122.419416)",H55,1,7,0,Local,0.0000

In [9]:
data.loc[data['Race']=='Total','Race']=0
data.loc[data['Race']=='White','Race']=1
data.loc[data['Race']=='Hispanic or Latino','Race']=2
data.loc[data['Race']=='Black or African American','Race']=3

data.loc[data['Race']=='Asian','Race']=4
data.loc[data['Race']=='Multiple Race','Race']=5
data.loc[data['Race']=='Native Hawaiian or Other Pacific Islander','Race']=6
data.loc[data['Race']=='American Indian or Alaska Native','Race']=7

In [10]:
data.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",335.0,Female,2,4,"(29.760427, -95.369803)",H49,1,4,0,Local,7.4793
1,2,1997,"Houston, TX",0,Currently drank alcohol,"at least one drink of alcohol, on at least 1 d...",382.0,Total,3,4,"(29.760427, -95.369803)",H42,0,3,0,Local,49.6852
2,3,1993,Nevada,0,Had their first drink of alcohol before age 13...,other than a few sips,196.0,Female,1,0,"(39.493240390000494, -117.07184056399967)",H41,1,6,2,State,47.8132
3,4,2017,Pennsylvania,1,Ever used cocaine,"any form of cocaine, such as powder, crack, or...",104.0,Male,4,4,"(40.79373015200048, -77.86070029399963)",H49,2,2,0,State,3.4554
4,5,2007,"San Francisco, CA",1,Ever took steroids without a doctor's prescrip...,"pills or shots, one or more times during their...",100.0,Female,5,4,"(37.77493, -122.419416)",H55,1,7,0,Local,0.0000

In [11]:
#data['Race']

In [12]:
data['Greater_Risk_Question'].value_counts()

Currently used marijuana                                                                                                     4421
Had their first drink of alcohol before age 13 years                                                                         4265
Tried marijuana for the first time before age 13 years                                                                       4247
Currently drank alcohol                                                                                                      4204
Ever used cocaine                                                                                                            4072
Were offered, sold, or given an illegal drug on school property                                                              3894
Ever used marijuana                                                                                                          3734
Ever injected any illegal drug                                                                                               3581
Ever used inhalants                                                                                                          3509
Ever took steroids without a doctor's prescription                                                                           3470
Ever drank alcohol                                                                                                           3462
Ever used methamphetamines                                                                                                   3331
Ever used heroin                                                                                                             3294
Ever used ecstasy                                                                                                            2665
Usually got the alcohol they drank by someone giving it to them                                                               858
Reported 10 or more as the largest number of drinks they had in a row                                                         773
Ever used synthetic marijuana                                                                                                 691
Reported current binge drinking                                                                                               439
Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it     387
Ever used hallucinogenic drugs                                                                                                102
Name: Greater_Risk_Question, dtype: int64

In [13]:
data.loc[data['Greater_Risk_Question']=='Currently used marijuana','Greater_Risk_Question']=0
data.loc[data['Greater_Risk_Question']=='Had their first drink of alcohol before age 13 years','Greater_Risk_Question']=1

data.loc[data['Greater_Risk_Question']=='Tried marijuana for the first time before age 13 years','Greater_Risk_Question']=2
data.loc[data['Greater_Risk_Question']=='Currently drank alcohol','Greater_Risk_Question']=3
data.loc[data['Greater_Risk_Question']=='Ever used cocaine','Greater_Risk_Question']=4
data.loc[data['Greater_Risk_Question']=='Were offered, sold, or given an illegal drug on school property','Greater_Risk_Question']=5
data.loc[data['Greater_Risk_Question']=='Ever used marijuana','Greater_Risk_Question']=6
data.loc[data['Greater_Risk_Question']=='Ever injected any illegal drug','Greater_Risk_Question']=7
data.loc[data['Greater_Risk_Question']=='Ever used inhalants','Greater_Risk_Question']=8
data.loc[data['Greater_Risk_Question']=="Ever took steroids without a doctor's prescription",'Greater_Risk_Question']=9


data.loc[data['Greater_Risk_Question']=='Ever drank alcohol','Greater_Risk_Question']=10
data.loc[data['Greater_Risk_Question']=='Ever used methamphetamines','Greater_Risk_Question']=11
data.loc[data['Greater_Risk_Question']=='Ever used heroin','Greater_Risk_Question']=12
data.loc[data['Greater_Risk_Question']=='Ever used ecstasy','Greater_Risk_Question']=13


data.loc[data['Greater_Risk_Question']=='Usually got the alcohol they drank by someone giving it to them','Greater_Risk_Question']=14
data.loc[data['Greater_Risk_Question']=='Reported 10 or more as the largest number of drinks they had in a row','Greater_Risk_Question']=15
data.loc[data['Greater_Risk_Question']=='Ever used synthetic marijuana','Greater_Risk_Question']=16

data.loc[data['Greater_Risk_Question']=='Reported current binge drinking','Greater_Risk_Question']=17
data.loc[data['Greater_Risk_Question']=='Reported current binge drinking','Greater_Risk_Question']=18
data.loc[data['Greater_Risk_Question']=="Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it",'Greater_Risk_Question']=19
data.loc[data['Greater_Risk_Question']=='Ever used hallucinogenic drugs','Greater_Risk_Question']=20

In [14]:
data.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,4,"any form of cocaine, such as powder, crack, or...",335.0,Female,2,4,"(29.760427, -95.369803)",H49,1,4,0,Local,7.4793
1,2,1997,"Houston, TX",0,3,"at least one drink of alcohol, on at least 1 d...",382.0,Total,3,4,"(29.760427, -95.369803)",H42,0,3,0,Local,49.6852
2,3,1993,Nevada,0,1,other than a few sips,196.0,Female,1,0,"(39.493240390000494, -117.07184056399967)",H41,1,6,2,State,47.8132
3,4,2017,Pennsylvania,1,4,"any form of cocaine, such as powder, crack, or...",104.0,Male,4,4,"(40.79373015200048, -77.86070029399963)",H49,2,2,0,State,3.4554
4,5,2007,"San Francisco, CA",1,9,"pills or shots, one or more times during their...",100.0,Female,5,4,"(37.77493, -122.419416)",H55,1,7,0,Local,0.0000

In [15]:
data['Greater_Risk_Question'].value_counts()

0     4421
1     4265
2     4247
3     4204
4     4072
5     3894
6     3734
7     3581
8     3509
9     3470
10    3462
11    3331
12    3294
13    2665
14     858
15     773
16     691
17     439
19     387
20     102
Name: Greater_Risk_Question, dtype: int64

In [16]:
data.loc[data['Sex']=='Male','Sex']=0
data.loc[data['Sex']=='Female','Sex']=1
data.loc[data['Sex']=='Total','Sex']=2

In [17]:
data['Sex'].value_counts()

2    22057
1    16973
0    16369
Name: Sex, dtype: int64

In [18]:
data.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,4,"any form of cocaine, such as powder, crack, or...",335.0,1,2,4,"(29.760427, -95.369803)",H49,1,4,0,Local,7.4793
1,2,1997,"Houston, TX",0,3,"at least one drink of alcohol, on at least 1 d...",382.0,2,3,4,"(29.760427, -95.369803)",H42,0,3,0,Local,49.6852
2,3,1993,Nevada,0,1,other than a few sips,196.0,1,1,0,"(39.493240390000494, -117.07184056399967)",H41,1,6,2,State,47.8132
3,4,2017,Pennsylvania,1,4,"any form of cocaine, such as powder, crack, or...",104.0,0,4,4,"(40.79373015200048, -77.86070029399963)",H49,2,2,0,State,3.4554
4,5,2007,"San Francisco, CA",1,9,"pills or shots, one or more times during their...",100.0,1,5,4,"(37.77493, -122.419416)",H55,1,7,0,Local,0.0000

In [19]:
data['Sex'].value_counts()

2    22057
1    16973
0    16369
Name: Sex, dtype: int64

In [20]:
data['StratificationType'].value_counts()

State        31878
Local        18129
Territory     2467
National      2276
Other          649
Name: StratificationType, dtype: int64

In [21]:
data.loc[data['StratificationType']=='State','StratificationType']=0
data.loc[data['StratificationType']=='Local','StratificationType']=1
data.loc[data['StratificationType']=='Territory','StratificationType']=2
data.loc[data['StratificationType']=='National','StratificationType']=3
data.loc[data['StratificationType']=='Other','StratificationType']=4

In [22]:
data.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,4,"any form of cocaine, such as powder, crack, or...",335.0,1,2,4,"(29.760427, -95.369803)",H49,1,4,0,1,7.4793
1,2,1997,"Houston, TX",0,3,"at least one drink of alcohol, on at least 1 d...",382.0,2,3,4,"(29.760427, -95.369803)",H42,0,3,0,1,49.6852
2,3,1993,Nevada,0,1,other than a few sips,196.0,1,1,0,"(39.493240390000494, -117.07184056399967)",H41,1,6,2,0,47.8132
3,4,2017,Pennsylvania,1,4,"any form of cocaine, such as powder, crack, or...",104.0,0,4,4,"(40.79373015200048, -77.86070029399963)",H49,2,2,0,0,3.4554
4,5,2007,"San Francisco, CA",1,9,"pills or shots, one or more times during their...",100.0,1,5,4,"(37.77493, -122.419416)",H55,1,7,0,1,0.0000

In [23]:
data['QuestionCode'].value_counts()

H48             4421
H41             4265
H47             4247
H42             4204
H49             4072
H58             3894
H46             3734
H57             3581
H50             3509
H55             3470
H40             3462
H52             3331
H51             3294
H53             2665
H43              858
H45              773
H54              691
H44              439
H56              387
QNHALLUCDRUG     102
Name: QuestionCode, dtype: int64

In [24]:
def remove_H(x):
    return x.replace('H','')

In [40]:
data['QuestionCode']=data['QuestionCode'].apply(remove_H)
data.loc[data['QuestionCode']=='QNALLUCDRUG','QuestionCode']=59

In [41]:
data.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType,Greater_Risk_Probability
0,1,1995,"Houston, TX",1,4,"any form of cocaine, such as powder, crack, or...",335.0,1,2,4,"(29.760427, -95.369803)",49,1,4,0,1,7.4793
1,2,1997,"Houston, TX",0,3,"at least one drink of alcohol, on at least 1 d...",382.0,2,3,4,"(29.760427, -95.369803)",42,0,3,0,1,49.6852
2,3,1993,Nevada,0,1,other than a few sips,196.0,1,1,0,"(39.493240390000494, -117.07184056399967)",41,1,6,2,0,47.8132
3,4,2017,Pennsylvania,1,4,"any form of cocaine, such as powder, crack, or...",104.0,0,4,4,"(40.79373015200048, -77.86070029399963)",49,2,2,0,0,3.4554
4,5,2007,"San Francisco, CA",1,9,"pills or shots, one or more times during their...",100.0,1,5,4,"(37.77493, -122.419416)",55,1,7,0,1,0.0000

In [42]:
data['QuestionCode'].value_counts()

48    4421
41    4265
47    4247
42    4204
49    4072
58    3894
46    3734
57    3581
50    3509
55    3470
40    3462
52    3331
51    3294
53    2665
43     858
45     773
54     691
44     439
56     387
59     102
Name: QuestionCode, dtype: int64

In [43]:

dataset = data.drop(columns=['Patient_ID','LocationDesc','Description','GeoLocation','Greater_Risk_Probability'])

In [44]:
y = data['Greater_Risk_Probability']
y.head()

0     7.4793
1    49.6852
2    47.8132
3     3.4554
4     0.0000
Name: Greater_Risk_Probability, dtype: float64

In [45]:
dataset.head()

,YEAR,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,1995,1,4,335.0,1,2,4,49,1,4,0,1
1,1997,0,3,382.0,2,3,4,42,0,3,0,1
2,1993,0,1,196.0,1,1,0,41,1,6,2,0
3,2017,1,4,104.0,0,4,4,49,2,2,0,0
4,2007,1,9,100.0,1,5,4,55,1,7,0,1


# Splitting the data into training and testing data

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train,X_test,y_train,y_test = train_test_split(dataset,y,test_size=0.3)

In [48]:
X_train.shape

(38779, 12)

In [49]:
X_test.shape

(16620, 12)

In [50]:
y_train.shape

(38779,)

In [51]:
y_test.shape

(16620,)


# Model Selection

In [144]:
from sklearn.ensemble import RandomForestRegressor

In [153]:
reg = RandomForestRegressor(n_estimators=20,verbose=1)

In [154]:
reg.fit(X_train,y_train)

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    3.5s finished

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
           oob_score=False, random_state=None, verbose=1, warm_start=False)

In [155]:
y_predict = reg.predict(X_test)

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.2s finished

# Evaluating the model

In [156]:
from sklearn.metrics import mean_squared_error,r2_score

In [157]:
error = mean_squared_error(y_test,y_predict)

In [158]:
error

38.728022489530254

In [159]:
reg.score(X_train,y_train)

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.4s finished

0.9854108298612401

In [160]:
r2_score(y_test,y_predict)

0.9064640922674525

In [161]:
print('Accuracy of the model',reg.score(X_train,y_train)*100,'%')

Accuracy of the model 98.54108298612401 %

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.4s finished

# Ridge Regression=41.449996987851335 %
# Random Forest Regressor  = 98.310%
# GradientBoostingRegressor=  89.06526233300269 %

# Predicting the model on the test dataset

In [167]:

data1= pd.read_csv('test_file.csv')
data1.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,55400,2007,Navajo,1,Ever used marijuana,"also called grass, pot, or weed, one or more t...",157.0,Male,Hispanic or Latino,3,NaN,H46,2,4,1,Other
1,55401,2001,Florida,1,Currently used marijuana,"also called grass, pot, or weed, one or more t...",724.0,Total,Total,2,"(28.932040377000476, -81.92896053899966)",H48,0,0,4,State
2,55402,2005,"Charlotte-Mecklenburg County, NC",1,"Were offered, sold, or given an illegal drug o...",during the 12 months before the survey,105.0,Male,Hispanic or Latino,4,"(35.227087, -80.843127)",H58,2,4,0,Local
3,55403,2017,Nevada,1,Ever used synthetic marijuana,"also called ""K2,"" ""Spice,"" ""fake weed,"" ""King ...",157.0,Male,Total,2,"(39.493240390000494, -117.07184056399967)",H54,2,0,4,State
4,55404,2007,Illinois,1,Ever used heroin,"also called ""smack,"" ""junk,"" or ""China White,""...",174.0,Total,Black or African American,1,"(40.48501028300046, -88.99771017799969)",H51,0,3,3,State

# Test data Preprocessing

In [168]:
data1.loc[data1['Race']=='Total','Race']=0
data1.loc[data1['Race']=='White','Race']=1
data1.loc[data1['Race']=='Hispanic or Latino','Race']=2
data1.loc[data1['Race']=='Black or African American','Race']=3

data1.loc[data1['Race']=='Asian','Race']=4
data1.loc[data1['Race']=='Multiple Race','Race']=5
data1.loc[data1['Race']=='Native Hawaiian or Other Pacific Islander','Race']=6
data1.loc[data1['Race']=='American Indian or Alaska Native','Race']=7

In [171]:
data1.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,55400,2007,Navajo,1,6,"also called grass, pot, or weed, one or more t...",157.0,Male,2,3,NaN,H46,2,4,1,Other
1,55401,2001,Florida,1,0,"also called grass, pot, or weed, one or more t...",724.0,Total,0,2,"(28.932040377000476, -81.92896053899966)",H48,0,0,4,State
2,55402,2005,"Charlotte-Mecklenburg County, NC",1,5,during the 12 months before the survey,105.0,Male,2,4,"(35.227087, -80.843127)",H58,2,4,0,Local
3,55403,2017,Nevada,1,16,"also called ""K2,"" ""Spice,"" ""fake weed,"" ""King ...",157.0,Male,0,2,"(39.493240390000494, -117.07184056399967)",H54,2,0,4,State
4,55404,2007,Illinois,1,12,"also called ""smack,"" ""junk,"" or ""China White,""...",174.0,Total,3,1,"(40.48501028300046, -88.99771017799969)",H51,0,3,3,State

In [170]:
data1.loc[data1['Greater_Risk_Question']=='Currently used marijuana','Greater_Risk_Question']=0
data1.loc[data1['Greater_Risk_Question']=='Had their first drink of alcohol before age 13 years','Greater_Risk_Question']=1

data1.loc[data1['Greater_Risk_Question']=='Tried marijuana for the first time before age 13 years','Greater_Risk_Question']=2
data1.loc[data1['Greater_Risk_Question']=='Currently drank alcohol','Greater_Risk_Question']=3
data1.loc[data1['Greater_Risk_Question']=='Ever used cocaine','Greater_Risk_Question']=4
data1.loc[data1['Greater_Risk_Question']=='Were offered, sold, or given an illegal drug on school property','Greater_Risk_Question']=5
data1.loc[data1['Greater_Risk_Question']=='Ever used marijuana','Greater_Risk_Question']=6
data1.loc[data1['Greater_Risk_Question']=='Ever injected any illegal drug','Greater_Risk_Question']=7
data1.loc[data1['Greater_Risk_Question']=='Ever used inhalants','Greater_Risk_Question']=8
data1.loc[data1['Greater_Risk_Question']=="Ever took steroids without a doctor's prescription",'Greater_Risk_Question']=9


data1.loc[data1['Greater_Risk_Question']=='Ever drank alcohol','Greater_Risk_Question']=10
data1.loc[data1['Greater_Risk_Question']=='Ever used methamphetamines','Greater_Risk_Question']=11
data1.loc[data1['Greater_Risk_Question']=='Ever used heroin','Greater_Risk_Question']=12
data1.loc[data1['Greater_Risk_Question']=='Ever used ecstasy','Greater_Risk_Question']=13


data1.loc[data1['Greater_Risk_Question']=='Usually got the alcohol they drank by someone giving it to them','Greater_Risk_Question']=14
data1.loc[data1['Greater_Risk_Question']=='Reported 10 or more as the largest number of drinks they had in a row','Greater_Risk_Question']=15
data1.loc[data1['Greater_Risk_Question']=='Ever used synthetic marijuana','Greater_Risk_Question']=16

data1.loc[data1['Greater_Risk_Question']=='Reported current binge drinking','Greater_Risk_Question']=17
data1.loc[data1['Greater_Risk_Question']=='Reported current binge drinking','Greater_Risk_Question']=18
data1.loc[data1['Greater_Risk_Question']=="Ever took prescription pain medicine without a doctor's prescription or differently than how a doctor told them to use it",'Greater_Risk_Question']=19
data1.loc[data1['Greater_Risk_Question']=='Ever used hallucinogenic drugs','Greater_Risk_Question']=20

In [172]:
patient_id = data1.Patient_ID

In [173]:
data1.loc[data1['Sex']=='Male','Sex']=0
data1.loc[data1['Sex']=='Female','Sex']=1
data1.loc[data1['Sex']=='Total','Sex']=2

In [174]:
data1.loc[data1['StratificationType']=='State','StratificationType']=0
data1.loc[data1['StratificationType']=='Local','StratificationType']=1
data1.loc[data1['StratificationType']=='Territory','StratificationType']=2
data1.loc[data1['StratificationType']=='National','StratificationType']=3
data1.loc[data1['StratificationType']=='Other','StratificationType']=4

In [175]:
data1['QuestionCode']=data1['QuestionCode'].apply(remove_H)
data1.loc[data1['QuestionCode']=='QNALLUCDRUG','QuestionCode']=59

In [176]:
data1.head()

,Patient_ID,YEAR,LocationDesc,Subtopic,Greater_Risk_Question,Description,Sample_Size,Sex,Race,Grade,GeoLocation,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,55400,2007,Navajo,1,6,"also called grass, pot, or weed, one or more t...",157.0,0,2,3,NaN,46,2,4,1,4
1,55401,2001,Florida,1,0,"also called grass, pot, or weed, one or more t...",724.0,2,0,2,"(28.932040377000476, -81.92896053899966)",48,0,0,4,0
2,55402,2005,"Charlotte-Mecklenburg County, NC",1,5,during the 12 months before the survey,105.0,0,2,4,"(35.227087, -80.843127)",58,2,4,0,1
3,55403,2017,Nevada,1,16,"also called ""K2,"" ""Spice,"" ""fake weed,"" ""King ...",157.0,0,0,2,"(39.493240390000494, -117.07184056399967)",54,2,0,4,0
4,55404,2007,Illinois,1,12,"also called ""smack,"" ""junk,"" or ""China White,""...",174.0,2,3,1,"(40.48501028300046, -88.99771017799969)",51,0,3,3,0

In [177]:
y1_test = data1.drop(columns=['Patient_ID','LocationDesc','Description','GeoLocation'])

In [178]:
y1_test.head()

,YEAR,Subtopic,Greater_Risk_Question,Sample_Size,Sex,Race,Grade,QuestionCode,StratID1,StratID2,StratID3,StratificationType
0,2007,1,6,157.0,0,2,3,46,2,4,1,4
1,2001,1,0,724.0,2,0,2,48,0,0,4,0
2,2005,1,5,105.0,0,2,4,58,2,4,0,1
3,2017,1,16,157.0,0,0,2,54,2,0,4,0
4,2007,1,12,174.0,2,3,1,51,0,3,3,0

In [179]:
y1_predict = reg.predict(y1_test)

[Parallel(n_jobs=1)]: Done  20 out of  20 | elapsed:    0.4s finished

In [180]:
y1_predict

array([53.988055, 34.341775, 46.02955 , ..., 16.01286 ,  3.212575,
       62.763245])

In [208]:
opdf = pd.DataFrame(data=y1_predict,index=patient_id)

In [211]:
opdf.head()

                    0
Patient_ID
55400       53.988055
55401       34.341775
55402       46.029550
55403       20.809480
55404        8.394770

In [210]:
opdf.to_csv('Output.csv')